services:
  mysql80:
    image: mysql:8.0
    container_name: mysql80
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: db
      MYSQL_USER: root80
      MYSQL_PASSWORD: mysql123
    ports:
      - "3308:3306"   # host:container
    volumes:
      - ./mysql80:/var/lib/mysql
    networks:
      - web

networks:
  web:
    external: true
